language: java
script: mvn clean install -Pengine-integration,webapps-integration,clean-db,jboss,h2 -am -pl qa/integration-tests-engine,qa/integration-tests-webapps
  -B -U -q
jdk:
- oraclejdk7
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
env:
  global:
  - secure: QExaONYPMHrKHdKI0fNSR0M+waFmx7jwH8bm9DyhdcZ8DlD+tS9fBJbma/nGBwnRlWDPutS7hv1SAR98jXmOEk+OjvKrHhVdbtVtiKoPdQSWiDd+wGl4Y6+n4CoBA52H7VhFpRx+jctxxjIHFQ7jlIUQCgGDpWrgfQhodN1jKUQ=
  - secure: w7CT463sfgTlyLHuWBPv/Q0u0MUvfJQWbzRt/fN0NodqMVJHcM5+xZy6wk+1AfTvB9/fO6gVLjt7okUEffZ2gU95GyGkLdDkWaZ8aai0yzDYKVv5sz9QFXXdUJdXvzkcjyDE80LCRfLZOu/MVzuJtyBk/tmslBxXDqha6iqkm1o=
  - secure: lnqNQF+SVCX180+xQ/2rt0xTreGuXRzn0jL9T7XdZvhHQzE6iiwh83ub1+54eBK16PjfNNKShNSvbenQoSuZQHEGAMIB1B7G7l0NMvSz7f54o/fZtv/zffGoZDcvXNpY0tG9G/QXp+WAW5/5Y/r5dpvDU7mX842XZmBOMh2Qw0o=
